### PR TITLE
Improvements to the about window

### PR DESCRIPTION
**Pull request by ErrorCatDev**
image

Hello, 

For this pull request, I improved the About window. Previously, the window will open at some place of the screen and extend outside of the screen boundary. This caused the Check For Updates button and some content to not be visible. Seeing that there are many possible future contributors in the about page, I added some features.

**Now:**
- The content is in a ScrollArea, with the background styled with the gradient.
- The whole window opens centred on-screen.
- The title bar is a lot cleaner now, so the 'About Writing Tools' text doesn't appear on both the titlebar and client area.
- The minimize button is disabled in the title bar, to look more like an about box.
- Minor formatting fixes.

**Known Issues**
- When right-clicking on links, the context menus appear transparent.
- Scrollbar style slightly different, but it is not very noticeable.

**What I'll add someday**
- A larger icon on the about box, like winver.

Apologies if I have messed anything up in the pull request process; this is my first time contributing on GitHub. Also, this is an amazing program! It's one of the few programs that I actually use. Keep up the great work!

### CODE REVIEW

**Comment by theJayTea** [comment]
Hi @ErrorCatDev, that's so cool, thank you so much for the pull request! You've done a great job for a first pull request, haha.
I'll test it out when I can (exam month right now, welp!), maybe optimize it a bit, and have this merged by the next update :)

**Comment by ErrorCatDev** [comment]
> Hi @ErrorCatDev, that's so cool, thank you so much for the pull request! You've done a great job for a first pull request, haha. I'll test it out when I can (exam month right now, welp!), maybe optimize it a bit, and have this merged by the next update :)

Thank you! I'll probably still be updating this thread over the next few days to fix the known issues. I'll mention you when it's all done. Meanwhile, good luck for your exams!

**Comment by ErrorCatDev** [comment]
> > Hi @ErrorCatDev, that's so cool, thank you so much for the pull request! You've done a great job for a first pull request, haha. I'll test it out when I can (exam month right now, welp!), maybe optimize it a bit, and have this merged by the next update :)

> Thank you! I'll probably still be updating this thread over the next few days to fix the known issues. I'll mention you when it's all done. Meanwhile, good luck for your exams!

@theJayTea Hello! Just mentioning you to inform that I have finally (hopefully) fixed all the known issues! No pressure to have this pull request merged - I understand that you are currently having your exams. Have a great day ahead!

**Comment by theJayTea** [comment]
Hi @ErrorCatDev, thank you so much for your support and contributions! We'll make sure they're reflected in the very About page you helped enhance haha. I'll merge it as soon as I can in the coming few days, and of course, we'll have it ready for the next update. I'm grateful to have you as a contributor!

**Comment by theJayTea** [comment]
Hi, so sorry for the delay in merging this. I’ll be releasing an update the coming week (exams are just ending), and it’ll be merged in time for that update :) Thanks again for your contributions here.

**Comment by ErrorCatDev** [comment]
> Hi, so sorry for the delay in merging this. I’ll be releasing an update the coming week (exams are just ending), and it’ll be merged in time for that update :) Thanks again for your contributions here.

@theJayTea No worries! All the best for the rest of your exams, and I look forward to v6 of WritingTools!

**Comment by theJayTea** [comment]
Thank you, @ErrorCatDev ! Soon, I'll also of course get you added to this About window itself, and also to the GitHub README :D

**Review by theJayTea — APPROVED** [review]

**Pull request merged**
