### PR TITLE
Add "Start on boot" option to the settings

### PR DESCRIPTION
**Pull request by Vadim-Karpenko**
image

### CODE REVIEW

**Comment by theJayTea** [comment]
Hey, thanks for your contribution!
The code looks fine but I haven't been able to test it yet as I have a ton of important workspaces open on my PC and can't restart haha (and not enough ram to fire up my VM), but I'll merge it as soon as I can test it further.

**Comment by hodanli** [comment]
Please add this feature.

**Comment by theJayTea** [comment]
So sorry for the delay with this - it’ll be merged by the next update (in w week-ish :)

**Comment by theJayTea** [comment]
Hi @Vadim-Karpenko ! Thank you again for this.
Since this was not automatically mergable (due to other changes since this PR was created), I reimplemented this and added additional checks to hide the option when running from source (for Linux users).

While I'll have to close this PR, my implementation of this was inspired by your implementation here, and I've given you full credit for this feature in the README and About section :)

Cheers!

**Pull request closed without merging**
